//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Место выдачи.
    /// </summary>
    // *** Start programmer edit section *** (МестоВыдачи CustomAttributes)

    // *** End programmer edit section *** (МестоВыдачи CustomAttributes)
    public enum МестоВыдачи
    {
        
        // *** Start programmer edit section *** (МестоВыдачи.Машиностроителей CustomAttributes)

        // *** End programmer edit section *** (МестоВыдачи.Машиностроителей CustomAttributes)
        Машиностроителей,
        
        // *** Start programmer edit section *** (МестоВыдачи.141 CustomAttributes)

        // *** End programmer edit section *** (МестоВыдачи.141 CustomAttributes)
        141,
        
        // *** Start programmer edit section *** (МестоВыдачи.Взлетная CustomAttributes)

        // *** End programmer edit section *** (МестоВыдачи.Взлетная CustomAttributes)
        Взлетная,
        
        // *** Start programmer edit section *** (МестоВыдачи.123 CustomAttributes)

        // *** End programmer edit section *** (МестоВыдачи.123 CustomAttributes)
        123,
    }
}
