//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "КодСотр as \'Код сотр\'",
            "ФИО as \'ФИО\'"})]
    [View("СотрудникL", new string[] {
            "КодСотр as \'Код сотр\'",
            "ФИО as \'ФИО\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодСотр;
        
        private string fФИО;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// КодСотр.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.КодСотр CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.КодСотр CustomAttributes)
        public virtual int КодСотр
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.КодСотр Get start)

                // *** End programmer edit section *** (Сотрудник.КодСотр Get start)
                int result = this.fКодСотр;
                // *** Start programmer edit section *** (Сотрудник.КодСотр Get end)

                // *** End programmer edit section *** (Сотрудник.КодСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.КодСотр Set start)

                // *** End programmer edit section *** (Сотрудник.КодСотр Set start)
                this.fКодСотр = value;
                // *** Start programmer edit section *** (Сотрудник.КодСотр Set end)

                // *** End programmer edit section *** (Сотрудник.КодСотр Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Get start)

                // *** End programmer edit section *** (Сотрудник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудник.ФИО Get end)

                // *** End programmer edit section *** (Сотрудник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Set start)

                // *** End programmer edit section *** (Сотрудник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудник.ФИО Set end)

                // *** End programmer edit section *** (Сотрудник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.Test2.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.Test2.Сотрудник));
                }
            }
        }
    }
}
