//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав заказа.
    /// </summary>
    // *** Start programmer edit section *** (СоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (СоставЗаказа CustomAttributes)
    [AutoAltered()]
    [Caption("Состав заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставЗаказаE", new string[] {
            "Адрес",
            "КодСостЗак",
            "Количество",
            "НомерТел",
            "Состояние",
            "Стоимость"})]
    public class СоставЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодСостЗак;
        
        private IIS.Test2.МестоВыдачи fАдрес;
        
        private double fСтоимость;
        
        private int fКоличество;
        
        private IIS.Test2.Состояния fСостояние;
        
        private int fНомерТел;
        
        private IIS.Test2.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (СоставЗаказа CustomMembers)

        // *** End programmer edit section *** (СоставЗаказа CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Адрес CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Адрес CustomAttributes)
        public virtual IIS.Test2.МестоВыдачи Адрес
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Адрес Get start)

                // *** End programmer edit section *** (СоставЗаказа.Адрес Get start)
                IIS.Test2.МестоВыдачи result = this.fАдрес;
                // *** Start programmer edit section *** (СоставЗаказа.Адрес Get end)

                // *** End programmer edit section *** (СоставЗаказа.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Адрес Set start)

                // *** End programmer edit section *** (СоставЗаказа.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (СоставЗаказа.Адрес Set end)

                // *** End programmer edit section *** (СоставЗаказа.Адрес Set end)
            }
        }
        
        /// <summary>
        /// КодСостЗак.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.КодСостЗак CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.КодСостЗак CustomAttributes)
        public virtual int КодСостЗак
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.КодСостЗак Get start)

                // *** End programmer edit section *** (СоставЗаказа.КодСостЗак Get start)
                int result = this.fКодСостЗак;
                // *** Start programmer edit section *** (СоставЗаказа.КодСостЗак Get end)

                // *** End programmer edit section *** (СоставЗаказа.КодСостЗак Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.КодСостЗак Set start)

                // *** End programmer edit section *** (СоставЗаказа.КодСостЗак Set start)
                this.fКодСостЗак = value;
                // *** Start programmer edit section *** (СоставЗаказа.КодСостЗак Set end)

                // *** End programmer edit section *** (СоставЗаказа.КодСостЗак Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Количество CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Количество Get start)

                // *** End programmer edit section *** (СоставЗаказа.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СоставЗаказа.Количество Get end)

                // *** End programmer edit section *** (СоставЗаказа.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Количество Set start)

                // *** End programmer edit section *** (СоставЗаказа.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СоставЗаказа.Количество Set end)

                // *** End programmer edit section *** (СоставЗаказа.Количество Set end)
            }
        }
        
        /// <summary>
        /// НомерТел.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.НомерТел CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.НомерТел CustomAttributes)
        public virtual int НомерТел
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.НомерТел Get start)

                // *** End programmer edit section *** (СоставЗаказа.НомерТел Get start)
                int result = this.fНомерТел;
                // *** Start programmer edit section *** (СоставЗаказа.НомерТел Get end)

                // *** End programmer edit section *** (СоставЗаказа.НомерТел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.НомерТел Set start)

                // *** End programmer edit section *** (СоставЗаказа.НомерТел Set start)
                this.fНомерТел = value;
                // *** Start programmer edit section *** (СоставЗаказа.НомерТел Set end)

                // *** End programmer edit section *** (СоставЗаказа.НомерТел Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Состояние CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Состояние CustomAttributes)
        public virtual IIS.Test2.Состояния Состояние
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Состояние Get start)

                // *** End programmer edit section *** (СоставЗаказа.Состояние Get start)
                IIS.Test2.Состояния result = this.fСостояние;
                // *** Start programmer edit section *** (СоставЗаказа.Состояние Get end)

                // *** End programmer edit section *** (СоставЗаказа.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Состояние Set start)

                // *** End programmer edit section *** (СоставЗаказа.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (СоставЗаказа.Состояние Set end)

                // *** End programmer edit section *** (СоставЗаказа.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Стоимость CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Стоимость Get start)

                // *** End programmer edit section *** (СоставЗаказа.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (СоставЗаказа.Стоимость Get end)

                // *** End programmer edit section *** (СоставЗаказа.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Стоимость Set start)

                // *** End programmer edit section *** (СоставЗаказа.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (СоставЗаказа.Стоимость Set end)

                // *** End programmer edit section *** (СоставЗаказа.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Test2.Заказ.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Заказ CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Заказ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказ"})]
        public virtual IIS.Test2.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Get start)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Get start)
                IIS.Test2.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Get end)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Set start)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Set end)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставЗаказаE", typeof(IIS.Test2.СоставЗаказа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)
    public class DetailArrayOfСоставЗаказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Test2.DetailArrayOfСоставЗаказа members)

        // *** End programmer edit section *** (IIS.Test2.DetailArrayOfСоставЗаказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставЗаказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставЗаказа.
        /// </summary>
        public DetailArrayOfСоставЗаказа(IIS.Test2.Заказ fЗаказ) : 
                base(typeof(СоставЗаказа), ((ICSSoft.STORMNET.DataObject)(fЗаказ)))
        {
        }
        
        public IIS.Test2.СоставЗаказа this[int index]
        {
            get
            {
                return ((IIS.Test2.СоставЗаказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Test2.СоставЗаказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
